add pyinstaller extraction and decompilation
CybercentreCanada/assemblyline-service-extract pull request #256
Opened 2024-04-05 13:50 UTC by cccs-ml

* extract pyc files from executables built by pyinstaller.
* decompile extracted pyc files (up to py version 3.8).

2024-04-05 14:24 UTC, gdesmar requested changes

2024-04-05 14:24 UTC, gdesmar commented on tests/samples/6458981df004b4c8a6139fb9550472b46fae9c2fb134bba5ab68ba70d943ec76.cart
Since those executable files can be a little harder to look at compared to a plaintext file, would it be possible to document them just a little in the README.md. Thank you! 🙂

2024-04-16 12:33 UTC, cccs-ml commented on tests/samples/6458981df004b4c8a6139fb9550472b46fae9c2fb134bba5ab68ba70d943ec76.cart
commit 6c60b55a8e623fe31dc3736ccfceff4123581db8

2024-05-03 13:35 UTC, gdesmar approved these changes

2024-05-03 13:38 UTC, merged