adding functionality to handle password protected office files
CybercentreCanada/assemblyline-service-extract pull request #3
Opened 2020-12-15 20:58 UTC by CCCS-MA

Made some changes to have extract receive password protected office files (tested with doc, docx, docm, xls, xlsx, xlsm, ppt, pptx file types) and to decrypt those files prior to being sent to other services. This avoids the issue of services like Cuckoo not being able to handle password protected files at this time.

2020-12-16 00:44 UTC, cccs-jp commented on extract/extract.py
> +        if request.file_type != "document/office/passwordprotected":
I think this is pretty cool

2020-12-16 00:44 UTC, cccs-jp commented on extract/extract.py
>              if os.path.isfile("/opt/al/support/extract/msoffice/bin/msoffice-crypt.exe"):
Is this a windows binary?  (.exe)  Weird

2020-12-16 00:44 UTC, cccs-jp commented on service_manifest.yml
>      name: Office password removed
A bit long.  Heuristic 10 is:  Extracted from Protected Archive, so perhap  "Extracted from Protected office document"

2020-12-16 00:44 UTC, cccs-jp commented on extract/ext/office_extract.py
> +        raise PasswordError("Could not find correct password")
Could you raise Heuristic EXTRACT.12 if we cannot find the password?

2020-12-16 12:50 UTC, cccs-kevin commented on extract/ext/office_extract.py
> +    # open the file in read-binary, assign value to file variable
redundant comment

2020-12-16 12:52 UTC, cccs-kevin commented on extract/ext/office_extract.py
> +    # checks new versions of office docs .***x i.e. .xlsx, .docx, etc.
this doesn't necessarily check for the version of office docs. Rather it checks for the parameters "EncryptionInfo" and "EncryptedPackage" in the OLE File, which based on our testing only exist in new versions of office docs .***x

2020-12-16 12:53 UTC, cccs-kevin commented on extract/ext/office_extract.py
We should raise the exception if "Failed to verify password" is not in e_repr

2020-12-16 12:54 UTC, cccs-kevin requested changes
See comments

2020-12-16 19:12 UTC, cccs-sgaron reviewed
We need to deconflict msoffcrypto lib and msoffice-crypt.exe before moving forward. Changes related to changing the name of the office document to document/office/passwordprotected are ok.

2020-12-16 19:12 UTC, cccs-sgaron commented on extract/ext/office_extract.py
> +import msoffcrypto
We were already running a msoffice-crypt.exe on office documents (https://github.com/CybercentreCanada/assemblyline-service-extract/blob/ac3ea1286341de687f16da34ffa07cc264a6b6cf/extract/ext/doc_extract.py#L436).

Are we sure that this is not just adding the same thing twice? Someone needs to test  msoffice-crypt.exe vs the msoffcrypto lib before merging this in. We need to know which is faster, which extract more documents and if we need to run both.

2020-12-16 20:59 UTC, cccs-kevin commented
We also need to add the pip package to the Dockerfile for msofficecrypto

2020-12-22 14:35 UTC, cccs-kevin approved these changes
🍨

2020-12-22 14:45 UTC, merged